/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'Pretendard', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      colors: {
        // shadcn/ui CSS variable bridge (preserved for component compatibility)
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Precision Sentinel Design System
        ds: {
          surface: '#f7f9fb',
          'surface-container': '#e8eff3',
          'surface-container-high': '#e1e9ee',
          'surface-container-low': '#f0f4f7',
          'surface-container-lowest': '#ffffff',
          'surface-container-highest': '#d9e4ea',
          'surface-dim': '#cfdce3',
          'surface-bright': '#f7f9fb',
          'surface-variant': '#d9e4ea',
          'on-surface': '#2a3439',
          'on-surface-variant': '#566166',
          primary: '#565e74',
          'primary-dim': '#4a5268',
          'primary-container': '#dae2fd',
          'primary-fixed': '#dae2fd',
          'primary-fixed-dim': '#ccd4ee',
          'on-primary': '#f7f7ff',
          'on-primary-container': '#4a5167',
          'on-primary-fixed': '#373f54',
          'on-primary-fixed-variant': '#535b71',
          secondary: '#526075',
          'secondary-dim': '#465469',
          'secondary-container': '#d5e3fd',
          'secondary-fixed': '#d5e3fd',
          'secondary-fixed-dim': '#c7d5ee',
          'on-secondary': '#f8f8ff',
          'on-secondary-container': '#455367',
          'on-secondary-fixed': '#324054',
          'on-secondary-fixed-variant': '#4e5c71',
          tertiary: '#005bc4',
          'tertiary-dim': '#004fad',
          'tertiary-container': '#4388fd',
          'tertiary-fixed': '#4388fd',
          'tertiary-fixed-dim': '#317bef',
          'on-tertiary': '#f9f8ff',
          'on-tertiary-container': '#000311',
          'on-tertiary-fixed': '#000000',
          'on-tertiary-fixed-variant': '#001435',
          error: '#9f403d',
          'error-dim': '#4e0309',
          'error-container': '#fe8983',
          'on-error': '#fff7f6',
          'on-error-container': '#752121',
          outline: '#717c82',
          'outline-variant': '#a9b4b9',
          'inverse-surface': '#0b0f10',
          'inverse-on-surface': '#9a9d9f',
          'inverse-primary': '#dae2fd',
          'surface-tint': '#565e74',
        },
      },
      borderRadius: {
        // shadcn vars
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        // Design system
        xl: '0.5rem',
        '2xl': '0.75rem',
      },
      boxShadow: {
        ambient: '0 12px 32px rgba(42, 52, 57, 0.06)',
        'ambient-md': '0 8px 24px rgba(42, 52, 57, 0.08)',
        'ambient-sm': '0 4px 12px rgba(42, 52, 57, 0.05)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
