"""Add analysis task and redundancy policy set tables

Revision ID: 0d3443650046
Revises: 96102c4e15f4
Create Date: 2025-10-31 15:25:21.238809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3443650046'
down_revision: Union[str, Sequence[str], None] = '96102c4e15f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysistasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('REDUNDANCY', name='analysistasktype'), nullable=False),
    sa.Column('task_status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILURE', name='analysistaskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysistasks_id'), 'analysistasks', ['id'], unique=False)
    op.create_table('redundancypolicysets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('UPPER', 'LOWER', name='redundancypolicysettype'), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['analysistasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redundancypolicysets_id'), 'redundancypolicysets', ['id'], unique=False)
    op.create_index(op.f('ix_redundancypolicysets_set_number'), 'redundancypolicysets', ['set_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redundancypolicysets_set_number'), table_name='redundancypolicysets')
    op.drop_index(op.f('ix_redundancypolicysets_id'), table_name='redundancypolicysets')
    op.drop_table('redundancypolicysets')
    op.drop_index(op.f('ix_analysistasks_id'), table_name='analysistasks')
    op.drop_table('analysistasks')
    # ### end Alembic commands ###
