"""Create initial schema

Revision ID: 4e930a9f1c8e
Revises:
Create Date: 2023-10-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e930a9f1c8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('object_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_logs_id'), 'change_logs', ['id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('vsys', sa.String(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('application', sa.String(), nullable=True),
    sa.Column('security_profile', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_rule_name'), 'policies', ['rule_name'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_table('network_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_objects_name'), 'network_objects', ['name'], unique=False)
    op.create_index(op.f('ix_network_objects_id'), 'network_objects', ['id'], unique=False)
    op.create_table('network_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('members', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_groups_name'), 'network_groups', ['name'], unique=False)
    op.create_index(op.f('ix_network_groups_id'), 'network_groups', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('service_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('members', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_groups_name'), 'service_groups', ['name'], unique=False)
    op.create_index(op.f('ix_service_groups_id'), 'service_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_groups_id'), table_name='service_groups')
    op.drop_index(op.f('ix_service_groups_name'), table_name='service_groups')
    op.drop_table('service_groups')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_network_groups_id'), table_name='network_groups')
    op.drop_index(op.f('ix_network_groups_name'), table_name='network_groups')
    op.drop_table('network_groups')
    op.drop_index(op.f('ix_network_objects_id'), table_name='network_objects')
    op.drop_index(op.f('ix_network_objects_name'), table_name='network_objects')
    op.drop_table('network_objects')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_rule_name'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_change_logs_id'), table_name='change_logs')
    op.drop_table('change_logs')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
