"""Add is_active and last_seen_at to models

Revision ID: 506be5600d50
Revises: 4e930a9f1c8e
Create Date: 2025-10-21 02:39:46.194080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506be5600d50'
down_revision: Union[str, Sequence[str], None] = '4e930a9f1c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('network_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('service_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('service_groups', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('network_objects', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('network_groups', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
