"""Add sync status to devices

Revision ID: 775a087473c7
Revises: 506be5600d50
Create Date: 2025-10-21 03:05:38.890602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775a087473c7'
down_revision: Union[str, Sequence[str], None] = '506be5600d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols = {col['name'] for col in inspector.get_columns('devices')}

    if 'last_sync_at' not in existing_cols:
        op.add_column('devices', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    if 'last_sync_status' not in existing_cols:
        op.add_column('devices', sa.Column('last_sync_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_sync_status')
    op.drop_column('devices', 'last_sync_at')
    # ### end Alembic commands ###
