"""Refactor sync status and remove ip_version

Revision ID: 96102c4e15f4
Revises: b66eeb2bdb5d
Create Date: 2025-10-30 14:38:52.015902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96102c4e15f4'
down_revision: Union[str, Sequence[str], None] = 'b66eeb2bdb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_step', sa.String(), nullable=True))

    with op.batch_alter_table('policy_address_members', schema=None) as batch_op:
        batch_op.drop_column('ip_version')
        # Recreate the index without ip_version.
        # First, drop the old index. The name is auto-generated by Alembic.
        batch_op.drop_index('ix_policy_addr_members_lookup')
        # Then, create the new one.
        batch_op.create_index('ix_policy_addr_members_lookup', ['device_id', 'direction', 'ip_start', 'ip_end'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_sync_step')

    with op.batch_alter_table('policy_address_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_version', sa.INTEGER(), nullable=True))
        # Recreate the old index with ip_version.
        batch_op.drop_index('ix_policy_addr_members_lookup')
        batch_op.create_index('ix_policy_addr_members_lookup', ['device_id', 'direction', 'ip_version', 'ip_start', 'ip_end'], unique=False)
