"""Add bidirectional relationship between Policy and RedundancyPolicySet

Revision ID: cea930c349cb
Revises: 5a0be6dd8ed0
Create Date: 2025-11-05 15:43:56.825485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea930c349cb'
down_revision: Union[str, Sequence[str], None] = '021c2a4e1680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
